"""initial schema

Revision ID: 6d7b2e1f1e68
Revises: 
Create Date: 2026-09-01 11:30:27.911846

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '6d7b2e1f1e68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siren', sa.String(), nullable=True),
    sa.Column('siret', sa.String(), nullable=True),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('forme_juridique', sa.String(), nullable=True),
    sa.Column('date_creation', sa.Date(), nullable=True),
    sa.Column('code_naf', sa.String(), nullable=True),
    sa.Column('activite', sa.String(), nullable=True),
    sa.Column('adresse', sa.String(), nullable=True),
    sa.Column('dirigeants', postgresql.JSONB(astext_type=Text()).with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('effectif', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=Text()).with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_siren'), 'companies', ['siren'], unique=False)
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siren', sa.String(), nullable=True),
    sa.Column('nom_entreprise', sa.String(), nullable=True),
    sa.Column('nom_normalise', sa.String(), nullable=True),
    sa.Column('type_proprietaire', sa.String(), nullable=False),
    sa.Column('categorie_juridique', sa.String(), nullable=True),
    sa.Column('activite_principale', sa.String(), nullable=True),
    sa.Column('date_creation', sa.Date(), nullable=True),
    sa.Column('tranche_effectifs', sa.String(), nullable=True),
    sa.Column('employeur', sa.Boolean(), nullable=True),
    sa.Column('cessation_activite', sa.Boolean(), nullable=True),
    sa.Column('nb_parcelles_api', sa.Integer(), nullable=False),
    sa.Column('nb_locaux_api', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=Text()).with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owners_nom_normalise'), 'owners', ['nom_normalise'], unique=False)
    op.create_index(op.f('ix_owners_siren'), 'owners', ['siren'], unique=True)
    op.create_index(op.f('ix_owners_type_proprietaire'), 'owners', ['type_proprietaire'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_parcelle', sa.String(), nullable=False),
    sa.Column('adresse_brute', sa.String(), nullable=True),
    sa.Column('adresse_normalisee', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('rue', sa.String(), nullable=True),
    sa.Column('code_postal', sa.String(), nullable=True),
    sa.Column('code_commune', sa.String(), nullable=True),
    sa.Column('ville', sa.String(), nullable=True),
    sa.Column('departement', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geometrie', postgresql.JSONB(astext_type=Text()).with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('contenance', sa.Float(), nullable=True),
    sa.Column('type_actif', sa.String(), nullable=True),
    sa.Column('type_actif_confidence', sa.String(), nullable=True),
    sa.Column('type_actif_indices', postgresql.JSONB(astext_type=Text()).with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('usage_batiment', sa.String(), nullable=True),
    sa.Column('surface_bati', sa.Float(), nullable=True),
    sa.Column('surface_batiment', sa.Float(), nullable=True),
    sa.Column('prix_derniere_mutation', sa.Float(), nullable=True),
    sa.Column('date_derniere_mutation', sa.Date(), nullable=True),
    sa.Column('nature_derniere_mutation', sa.String(), nullable=True),
    sa.Column('type_local_vente', sa.String(), nullable=True),
    sa.Column('nombre_lots_derniere_mutation', sa.Integer(), nullable=True),
    sa.Column('prix_m2', sa.Float(), nullable=True),
    sa.Column('prix_m2_fiable', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=Text()).with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_code_commune'), 'properties', ['code_commune'], unique=False)
    op.create_index(op.f('ix_properties_code_postal'), 'properties', ['code_postal'], unique=False)
    op.create_index(op.f('ix_properties_departement'), 'properties', ['departement'], unique=False)
    op.create_index(op.f('ix_properties_numero_parcelle'), 'properties', ['numero_parcelle'], unique=True)
    op.create_index(op.f('ix_properties_type_actif'), 'properties', ['type_actif'], unique=False)
    op.create_table('fonds_de_commerce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('activite', sa.String(), nullable=True),
    sa.Column('prix', sa.Float(), nullable=True),
    sa.Column('date_debut_activite', sa.Date(), nullable=True),
    sa.Column('categorie_vente', sa.String(), nullable=True),
    sa.Column('origine_fonds', sa.String(), nullable=True),
    sa.Column('acheteur', postgresql.JSONB(astext_type=Text()).with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('precedent_proprietaire', postgresql.JSONB(astext_type=Text()).with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('annonce_bodacc', postgresql.JSONB(astext_type=Text()).with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('fiabilite_appartenance_parcelle', sa.String(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=Text()).with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fonds_de_commerce_property_id'), 'fonds_de_commerce', ['property_id'], unique=False)
    op.create_table('occupants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('siren', sa.String(), nullable=True),
    sa.Column('siret', sa.String(), nullable=True),
    sa.Column('enseigne', sa.String(), nullable=True),
    sa.Column('nom_entreprise', sa.String(), nullable=True),
    sa.Column('activite_principale_etablissement', sa.String(), nullable=True),
    sa.Column('categorie_juridique', sa.String(), nullable=True),
    sa.Column('date_entree_lieux', sa.Date(), nullable=True),
    sa.Column('date_sortie_lieux', sa.Date(), nullable=True),
    sa.Column('etablissement_ferme', sa.Boolean(), nullable=True),
    sa.Column('cessation_activite', sa.Boolean(), nullable=True),
    sa.Column('fiabilite_appartenance_parcelle', sa.String(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=Text()).with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occupants_property_id'), 'occupants', ['property_id'], unique=False)
    op.create_table('owner_portfolio_api',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('numero_parcelle', sa.String(), nullable=True),
    sa.Column('adresse', sa.String(), nullable=True),
    sa.Column('commune', sa.String(), nullable=True),
    sa.Column('departement', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owner_portfolio_api_owner_id'), 'owner_portfolio_api', ['owner_id'], unique=False)
    op.create_table('ownership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('fiabilite_api', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('date_verification', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ownership_owner_id'), 'ownership', ['owner_id'], unique=False)
    op.create_index(op.f('ix_ownership_property_id'), 'ownership', ['property_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('asset_score', sa.Float(), nullable=False),
    sa.Column('owner_score', sa.Float(), nullable=False),
    sa.Column('sell_signal_score', sa.Float(), nullable=False),
    sa.Column('sourcing_score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=Text()).with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('score_explanation', sa.Text(), nullable=True),
    sa.Column('config_version', sa.String(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_property_id'), 'scores', ['property_id'], unique=False)
    op.create_index(op.f('ix_scores_sourcing_score'), 'scores', ['sourcing_score'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('prix', sa.Float(), nullable=True),
    sa.Column('surface', sa.Float(), nullable=True),
    sa.Column('type_mutation', sa.String(), nullable=True),
    sa.Column('prix_m2', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_property_id'), 'transactions', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_property_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_scores_sourcing_score'), table_name='scores')
    op.drop_index(op.f('ix_scores_property_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_ownership_property_id'), table_name='ownership')
    op.drop_index(op.f('ix_ownership_owner_id'), table_name='ownership')
    op.drop_table('ownership')
    op.drop_index(op.f('ix_owner_portfolio_api_owner_id'), table_name='owner_portfolio_api')
    op.drop_table('owner_portfolio_api')
    op.drop_index(op.f('ix_occupants_property_id'), table_name='occupants')
    op.drop_table('occupants')
    op.drop_index(op.f('ix_fonds_de_commerce_property_id'), table_name='fonds_de_commerce')
    op.drop_table('fonds_de_commerce')
    op.drop_index(op.f('ix_properties_type_actif'), table_name='properties')
    op.drop_index(op.f('ix_properties_numero_parcelle'), table_name='properties')
    op.drop_index(op.f('ix_properties_departement'), table_name='properties')
    op.drop_index(op.f('ix_properties_code_postal'), table_name='properties')
    op.drop_index(op.f('ix_properties_code_commune'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_owners_type_proprietaire'), table_name='owners')
    op.drop_index(op.f('ix_owners_siren'), table_name='owners')
    op.drop_index(op.f('ix_owners_nom_normalise'), table_name='owners')
    op.drop_table('owners')
    op.drop_index(op.f('ix_companies_siren'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
