"""add permis table

Revision ID: 7829421333dd
Revises: 6d7b2e1f1e68
Create Date: 2026-09-01 12:44:37.090374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7829421333dd'
down_revision = '6d7b2e1f1e68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('etat', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('date_autorisation', sa.Date(), nullable=True),
    sa.Column('demandeur_siren', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permis_property_id'), 'permis', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permis_property_id'), table_name='permis')
    op.drop_table('permis')
    # ### end Alembic commands ###
