"""add nature_batiment and occupant/fdc confidence_score+source

Revision ID: e45397ac4b71
Revises: 7829421333dd
Create Date: 2026-09-01 12:47:12.395988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45397ac4b71'
down_revision = '7829421333dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fonds_de_commerce', sa.Column('confidence_score', sa.Integer(), nullable=False))
    op.add_column('fonds_de_commerce', sa.Column('source', sa.String(), nullable=False))
    op.add_column('occupants', sa.Column('confidence_score', sa.Integer(), nullable=False))
    op.add_column('occupants', sa.Column('source', sa.String(), nullable=False))
    op.add_column('properties', sa.Column('nature_batiment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'nature_batiment')
    op.drop_column('occupants', 'source')
    op.drop_column('occupants', 'confidence_score')
    op.drop_column('fonds_de_commerce', 'source')
    op.drop_column('fonds_de_commerce', 'confidence_score')
    # ### end Alembic commands ###
